runner:
  eslint:
    cmd: npx eslint --format rdjson src/
    format: rdjson
    name: eslint

  tsc:
    cmd: npx tsc --noEmit --pretty false
    format: tsc
    name: TypeScript

  misspell:
    cmd: misspell src/
    format: misspell
    name: misspell

# Configurações por ferramenta
tools:
  eslint:
    level: error
    reporter: github-pr-review
    filter_mode: added

  typescript:
    level: warning
    reporter: github-pr-review
    filter_mode: diff_context
